version: '3.8'

services:
    tcpa-mysql:
        image: mysql:8.0
        container_name: tcpa-mysql-container
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: tcpa_database
            MYSQL_USER: tcpa_user
            MYSQL_PASSWORD: tcpa_pass
        networks:
            - tcpa_network

    tcpa-nginx:
        image: nginx:latest
        container_name: tcpa-nginx
        ports:
            - "${NGINX_PORT-8252}:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ../:/var/www/tcpa
        working_dir: /var/www/tcpa
        depends_on:
            - tcpa-php
        networks:
            - tcpa_network

    tcpa-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: tcpa-phpmyadmin
        environment:
            PMA_HOST: tcpa-mysql
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "${PHPMYADMIN_PORT-9292}:80"
        depends_on:
            - tcpa-mysql
        networks:
            - tcpa_network

    tcpa-php:
        container_name: tcpa-app
        image: tcpa-app
        build:
            context: .
            dockerfile: php/Dockerfile
        volumes:
            - ../:/var/www/tcpa
        networks:
            - tcpa_network

networks:
    tcpa_network:
        driver: bridge

